name: CI Build

on: [push]
  schedule:
    - cron: 0 12 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: pwd
      - name: Run a multi-line script
        run: |
          ls
          git status
     